-- ============================================================
-- Production Upgrade V2 — STEP 07: ADMIN / AUDIT HARDENING
-- Audits sensitive state transitions without storing document/PII payloads.
-- ============================================================

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_admin_audit_created on public.admin_audit_logs(created_at desc);
create index if not exists idx_admin_audit_entity on public.admin_audit_logs(entity_type,entity_id,created_at desc);
create index if not exists idx_admin_audit_actor on public.admin_audit_logs(actor_id,created_at desc);

alter table public.admin_audit_logs enable row level security;
drop policy if exists "admin_audit_admin_read" on public.admin_audit_logs;
create policy "admin_audit_admin_read" on public.admin_audit_logs for select using(public.is_admin_or_above());
revoke insert,update,delete on public.admin_audit_logs from anon,authenticated;
grant select on public.admin_audit_logs to authenticated,service_role;

create or replace function public.audit_sensitive_change()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_old jsonb := case when tg_op='INSERT' then '{}'::jsonb else to_jsonb(old) end;
  v_new jsonb := case when tg_op='DELETE' then '{}'::jsonb else to_jsonb(new) end;
  v_id text;
  v_details jsonb := '{}'::jsonb;
  v_should_log boolean := false;
begin
  v_id:=coalesce(v_new->>'id',v_old->>'id');

  if tg_table_name='profiles' then
    v_should_log := tg_op<>'UPDATE'
      or (v_old->>'role') is distinct from (v_new->>'role')
      or (v_old->>'seller_status') is distinct from (v_new->>'seller_status')
      or (v_old->>'account_status') is distinct from (v_new->>'account_status');
    v_details:=jsonb_build_object(
      'old_role',v_old->>'role','new_role',v_new->>'role',
      'old_provider_status',v_old->>'seller_status','new_provider_status',v_new->>'seller_status',
      'old_account_status',v_old->>'account_status','new_account_status',v_new->>'account_status'
    );
  elsif tg_table_name='seller_verifications' then
    v_should_log := tg_op<>'UPDATE' or (v_old->>'status') is distinct from (v_new->>'status');
    v_details:=jsonb_build_object('user_id',coalesce(v_new->>'user_id',v_old->>'user_id'),'old_status',v_old->>'status','new_status',v_new->>'status');
  elsif tg_table_name='appointments' then
    v_should_log := tg_op<>'UPDATE' or (v_old->>'status') is distinct from (v_new->>'status');
    v_details:=jsonb_build_object(
      'doctor_id',coalesce(v_new->>'doctor_id',v_old->>'doctor_id'),
      'patient_id',coalesce(v_new->>'patient_id',v_old->>'patient_id'),
      'old_status',v_old->>'status','new_status',v_new->>'status'
    );
  elsif tg_table_name='ambulance_services' then
    v_should_log := tg_op<>'UPDATE'
      or (v_old->>'is_verified') is distinct from (v_new->>'is_verified')
      or (v_old->>'is_available') is distinct from (v_new->>'is_available');
    v_details:=jsonb_build_object('old_verified',v_old->>'is_verified','new_verified',v_new->>'is_verified','old_available',v_old->>'is_available','new_available',v_new->>'is_available');
  elsif tg_table_name='doctor_provider_links' then
    v_should_log := tg_op<>'UPDATE' or (v_old->>'status') is distinct from (v_new->>'status');
    v_details:=jsonb_build_object('doctor_id',coalesce(v_new->>'doctor_id',v_old->>'doctor_id'),'provider_id',coalesce(v_new->>'provider_id',v_old->>'provider_id'),'old_status',v_old->>'status','new_status',v_new->>'status');
  elsif tg_table_name='blood_requests' then
    v_should_log := tg_op<>'UPDATE' or (v_old->>'status') is distinct from (v_new->>'status');
    v_details:=jsonb_build_object(
      'requester_id',coalesce(v_new->>'requester_id',v_old->>'requester_id'),
      'donor_id',coalesce(v_new->>'donor_id',v_old->>'donor_id'),
      'old_status',v_old->>'status','new_status',v_new->>'status'
    );
  end if;

  if v_should_log then
    insert into public.admin_audit_logs(actor_id,action,entity_type,entity_id,details)
    values(auth.uid(),lower(tg_op),tg_table_name,v_id,jsonb_strip_nulls(v_details));
  end if;
  if tg_op='DELETE' then return old; end if;
  return new;
end $$;

-- Replace only our audit triggers; business triggers remain untouched.
do $$ declare t text; begin
  foreach t in array array['profiles','seller_verifications','appointments','ambulance_services','doctor_provider_links','blood_requests'] loop
    execute format('drop trigger if exists %I on public.%I','trg_audit_'||t,t);
    execute format('create trigger %I after insert or update or delete on public.%I for each row execute procedure public.audit_sensitive_change()','trg_audit_'||t,t);
  end loop;
end $$;

create or replace function public.get_admin_audit_logs(p_limit integer default 100,p_offset integer default 0)
returns setof public.admin_audit_logs
language plpgsql stable security definer set search_path=public as $$
begin
  if not public.is_admin_or_above() then raise exception 'Admin access required.'; end if;
  return query select * from public.admin_audit_logs order by created_at desc
    limit greatest(1,least(coalesce(p_limit,100),500)) offset greatest(coalesce(p_offset,0),0);
end $$;
revoke all on function public.get_admin_audit_logs(integer,integer) from public;
grant execute on function public.get_admin_audit_logs(integer,integer) to authenticated,service_role;

notify pgrst, 'reload schema';
