import { useState } from "react";
import { CalendarDays,CheckCircle2,XCircle,Clock3,RotateCcw,UserX } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { useAppointments,updateAppointmentStatus,updateAppointment } from "@/hooks/useAppointments";
import { ROLES } from "@/constants/roles";
import LoadingSpinner from "@/components/shared/LoadingSpinner.jsx";
const labels={pending:"অপেক্ষমাণ",confirmed:"নিশ্চিত",cancelled:"বাতিল",completed:"সম্পন্ন",rescheduled:"পুনঃনির্ধারিত",no_show:"রোগী আসেননি"};
export default function AppointmentsPage(){
 const{user,role}=useAuth();const{appointments,loading,error,refresh}=useAppointments({role,userId:user?.id,enabled:[ROLES.DOCTOR,ROLES.HOSPITAL].includes(role)});const[busy,setBusy]=useState(null);
 async function change(a,status,extra={}){setBusy(a.id);const{error}=await updateAppointmentStatus(a.id,status,null,extra);setBusy(null);if(error)window.alert(error.message);else refresh();}
 async function cancel(a){const reason=window.prompt("বাতিল/প্রত্যাখ্যানের কারণ লিখুন:","");if(reason===null)return;if(!reason.trim()){window.alert("কারণ লিখতে হবে।");return;}change(a,"cancelled",{cancellation_reason:reason.trim()});}
 async function reschedule(a){const date=window.prompt("নতুন তারিখ (YYYY-MM-DD):",a.appointment_date||"");if(!date)return;const time=window.prompt("নতুন সময় (HH:MM):",a.appointment_time||"");if(!time)return;const reason=window.prompt("সময় পরিবর্তনের কারণ:","")||"Provider rescheduled";setBusy(a.id);const{error}=await updateAppointment(a.id,{appointment_date:date,appointment_time:time,reschedule_reason:reason,status:"rescheduled"});setBusy(null);if(error)window.alert(error.message);else refresh();}
 if(loading)return <LoadingSpinner fullScreen label="অ্যাপয়েন্টমেন্ট লোড হচ্ছে..."/>;
 return <div className="space-y-5"><div><h1 className="text-xl font-bold">অ্যাপয়েন্টমেন্ট</h1><p className="text-sm text-muted-foreground">রোগীর অনুরোধ নিশ্চিত, পুনঃনির্ধারণ, বাতিল ও সম্পন্ন করুন।</p></div>{error&&<div className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}{!appointments.length&&<div className="rounded-2xl border p-8 text-center text-sm text-muted-foreground">এখনো কোনো অ্যাপয়েন্টমেন্ট অনুরোধ নেই।</div>}<div className="space-y-3">{appointments.map(a=><div key={a.id} className="rounded-2xl border bg-card p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold">{a.patient_name||"রোগী"}</p><p className="mt-1 text-sm text-muted-foreground">{a.patient_phone||"ফোন দেওয়া হয়নি"}</p><div className="mt-3 flex flex-wrap gap-3 text-sm"><span className="flex items-center gap-1"><CalendarDays className="h-4 w-4 text-primary"/>{a.appointment_date}</span>{a.appointment_time&&<span className="flex items-center gap-1"><Clock3 className="h-4 w-4 text-primary"/>{a.appointment_time}</span>}</div>{a.appointment_number&&<p className="mt-1 text-xs text-muted-foreground">#{a.appointment_number}</p>}{a.note&&<p className="mt-2 rounded-lg bg-secondary p-2 text-sm">{a.note}</p>}{a.reschedule_reason&&<p className="mt-2 text-xs text-amber-700">সময় পরিবর্তন: {a.reschedule_reason}</p>}{a.cancellation_reason&&<p className="mt-2 text-xs text-destructive">বাতিল: {a.cancellation_reason}</p>}</div><span className="h-fit rounded-full bg-secondary px-3 py-1 text-xs font-medium">{labels[a.status]||a.status}</span></div>
 {a.status==='pending'&&<div className="mt-4 flex flex-wrap gap-2"><button disabled={busy===a.id} onClick={()=>change(a,'confirmed')} className="inline-flex min-h-10 items-center gap-1 rounded-xl bg-primary px-3 text-sm font-semibold text-primary-foreground"><CheckCircle2 className="h-4 w-4"/> নিশ্চিত করুন</button><button disabled={busy===a.id} onClick={()=>reschedule(a)} className="inline-flex min-h-10 items-center gap-1 rounded-xl border px-3 text-sm font-semibold"><RotateCcw className="h-4 w-4"/> সময় পরিবর্তন</button><button disabled={busy===a.id} onClick={()=>cancel(a)} className="inline-flex min-h-10 items-center gap-1 rounded-xl border px-3 text-sm font-semibold text-destructive"><XCircle className="h-4 w-4"/> বাতিল</button></div>}
 {['confirmed','rescheduled'].includes(a.status)&&<div className="mt-4 flex flex-wrap gap-2"><button disabled={busy===a.id} onClick={()=>change(a,'completed')} className="inline-flex min-h-10 items-center gap-1 rounded-xl bg-primary px-3 text-sm font-semibold text-primary-foreground"><CheckCircle2 className="h-4 w-4"/> পরামর্শ সম্পন্ন</button><button disabled={busy===a.id} onClick={()=>reschedule(a)} className="inline-flex min-h-10 items-center gap-1 rounded-xl border px-3 text-sm font-semibold"><RotateCcw className="h-4 w-4"/> পুনঃনির্ধারণ</button><button disabled={busy===a.id} onClick={()=>change(a,'no_show')} className="inline-flex min-h-10 items-center gap-1 rounded-xl border px-3 text-sm font-semibold"><UserX className="h-4 w-4"/> রোগী আসেননি</button><button disabled={busy===a.id} onClick={()=>cancel(a)} className="inline-flex min-h-10 items-center gap-1 rounded-xl border px-3 text-sm font-semibold text-destructive"><XCircle className="h-4 w-4"/> বাতিল</button></div>}
 </div>)}</div></div>;
}
