import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, CalendarX2, Save, Trash2 } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { ROLES, SELLER_STATUS } from "@/constants/roles";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import LoadingSpinner from "@/components/shared/LoadingSpinner.jsx";
import PendingApprovalNotice from "@/components/seller/PendingApprovalNotice.jsx";
import { addScheduleException, deleteScheduleException, fetchDoctorSchedule, loadScheduleContext, saveDaySchedule } from "@/services/scheduleService";

const DAYS=["রবিবার","সোমবার","মঙ্গলবার","বুধবার","বৃহস্পতিবার","শুক্রবার","শনিবার"];
const DEFAULT_DAY={enabled:false,start_time:"09:00",end_time:"17:00",slot_duration_minutes:30,break_start_time:"",break_end_time:""};

export default function SchedulePage(){
 const {user,role,sellerStatus}=useAuth();
 const [context,setContext]=useState({shop:null,doctors:[]}); const [doctorId,setDoctorId]=useState(""); const [days,setDays]=useState(()=>DAYS.map(()=>({...DEFAULT_DAY}))); const [exceptions,setExceptions]=useState([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [exceptionDate,setExceptionDate]=useState(""); const [exceptionNote,setExceptionNote]=useState("");
 const loadContext=useCallback(async()=>{if(!user)return;setLoading(true);const {data,error}=await loadScheduleContext(user.id,role);if(error)setMessage(error.message);setContext(data);const first=role===ROLES.DOCTOR?user.id:data.doctors?.[0]?.id||"";setDoctorId(first);setLoading(false);},[user?.id,role]);
 useEffect(()=>{loadContext();},[loadContext]);
 const loadDoctor=useCallback(async()=>{if(!doctorId||!context.shop?.id)return;const {schedules,exceptions:ex,error}=await fetchDoctorSchedule(doctorId,context.shop.id);if(error){setMessage(error.message);return;}const next=DAYS.map((_,i)=>{const s=schedules.find(x=>x.day_of_week===i);return s?{enabled:true,start_time:String(s.start_time).slice(0,5),end_time:String(s.end_time).slice(0,5),slot_duration_minutes:s.slot_duration_minutes,break_start_time:s.break_start_time?String(s.break_start_time).slice(0,5):"",break_end_time:s.break_end_time?String(s.break_end_time).slice(0,5):""}:{...DEFAULT_DAY};});setDays(next);setExceptions(ex);},[doctorId,context.shop?.id]);
 useEffect(()=>{loadDoctor();},[loadDoctor]);
 const selectedName=useMemo(()=>context.doctors?.find(d=>d.id===doctorId)?.full_name||"ডাক্তার",[context.doctors,doctorId]);
 function patchDay(i,patch){setDays(prev=>prev.map((d,idx)=>idx===i?{...d,...patch}:d));}
 async function saveAll(){if(!doctorId||!context.shop?.id)return;setSaving(true);setMessage("");for(let i=0;i<days.length;i++){const d=days[i];if(d.enabled&&d.end_time<=d.start_time){setMessage(`${DAYS[i]}: শেষ সময় শুরুর সময়ের পরে হতে হবে।`);setSaving(false);return;}if(d.enabled&&((d.break_start_time&&!d.break_end_time)||(!d.break_start_time&&d.break_end_time))){setMessage(`${DAYS[i]}: বিরতির শুরু ও শেষ দুটোই দিন।`);setSaving(false);return;}const {error}=await saveDaySchedule({doctorId,shopId:context.shop.id,dayOfWeek:i,enabled:d.enabled,startTime:d.start_time,endTime:d.end_time,slotDuration:d.slot_duration_minutes,breakStart:d.break_start_time,breakEnd:d.break_end_time});if(error){setMessage(error.message);setSaving(false);return;}}setSaving(false);setMessage("সময়সূচি সংরক্ষণ হয়েছে।");loadDoctor();}
 async function addException(){if(!exceptionDate)return;const {error}=await addScheduleException({doctorId,shopId:context.shop.id,date:exceptionDate,note:exceptionNote});if(error)setMessage(error.message);else{setExceptionDate("");setExceptionNote("");loadDoctor();}}
 async function removeException(id){await deleteScheduleException(id);loadDoctor();}
 if(sellerStatus!==SELLER_STATUS.APPROVED)return <PendingApprovalNotice status={sellerStatus} role={role}/>;
 if(loading)return <LoadingSpinner label="সময়সূচি লোড হচ্ছে..."/>;
 if(!context.shop)return <div className="rounded-2xl border p-8 text-center text-sm text-muted-foreground">আগে চেম্বার / হাসপাতালের তথ্য সম্পূর্ণ করুন।</div>;
 return <div className="space-y-6"><div><h1 className="text-xl font-bold">ডাক্তার সময়সূচি</h1><p className="mt-1 text-sm text-muted-foreground">সাপ্তাহিক সময়, slot duration, বিরতি ও ছুটির দিন নির্ধারণ করুন। Structured schedule থাকলে রোগী শুধু খালি slot বুক করতে পারবে।</p></div>
 {role===ROLES.HOSPITAL&&<div className="max-w-sm"><label className="text-sm font-medium">ডাক্তার নির্বাচন করুন<select className="mt-1 h-10 w-full rounded-lg border bg-card px-3" value={doctorId} onChange={e=>setDoctorId(e.target.value)}><option value="">ডাক্তার নির্বাচন করুন</option>{context.doctors.map(d=><option key={d.id} value={d.id}>{d.full_name}</option>)}</select></label></div>}
 {!doctorId?<div className="rounded-xl border p-6 text-sm text-muted-foreground">সময়সূচি সেট করতে আগে আমন্ত্রণ গ্রহণ করা ডাক্তার নির্বাচন করুন।</div>:<><section className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="border-b p-4"><div className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-primary"/><h2 className="font-semibold">{selectedName}</h2></div></div><div className="divide-y">{days.map((d,i)=><div key={DAYS[i]} className="grid gap-3 p-4 lg:grid-cols-[150px_1fr_1fr_120px_1fr_1fr]"><label className="flex items-center gap-2 font-medium"><input type="checkbox" checked={d.enabled} onChange={e=>patchDay(i,{enabled:e.target.checked})}/>{DAYS[i]}</label><Input type="time" disabled={!d.enabled} value={d.start_time} onChange={e=>patchDay(i,{start_time:e.target.value})}/><Input type="time" disabled={!d.enabled} value={d.end_time} onChange={e=>patchDay(i,{end_time:e.target.value})}/><select disabled={!d.enabled} className="h-10 rounded-lg border bg-background px-2 text-sm" value={d.slot_duration_minutes} onChange={e=>patchDay(i,{slot_duration_minutes:Number(e.target.value)})}>{[10,15,20,30,45,60].map(v=><option key={v} value={v}>{v} মিনিট</option>)}</select><Input type="time" disabled={!d.enabled} value={d.break_start_time} onChange={e=>patchDay(i,{break_start_time:e.target.value})} title="বিরতি শুরু"/><Input type="time" disabled={!d.enabled} value={d.break_end_time} onChange={e=>patchDay(i,{break_end_time:e.target.value})} title="বিরতি শেষ"/></div>)}</div><div className="border-t p-4"><Button onClick={saveAll} disabled={saving}><Save className="h-4 w-4"/>{saving?"সংরক্ষণ হচ্ছে...":"সময়সূচি সংরক্ষণ"}</Button></div></section>
 <section className="rounded-2xl border bg-card p-4 shadow-sm"><div className="flex items-center gap-2"><CalendarX2 className="h-5 w-5 text-primary"/><h2 className="font-semibold">ছুটি / অনুপস্থিতির দিন</h2></div><div className="mt-3 grid gap-2 sm:grid-cols-[180px_1fr_auto]"><Input type="date" min={new Date().toISOString().slice(0,10)} value={exceptionDate} onChange={e=>setExceptionDate(e.target.value)}/><Input placeholder="কারণ/নোট (ঐচ্ছিক)" value={exceptionNote} onChange={e=>setExceptionNote(e.target.value)}/><Button variant="outline" onClick={addException} disabled={!exceptionDate}>যোগ করুন</Button></div><div className="mt-3 space-y-2">{exceptions.map(e=><div key={e.id} className="flex items-center justify-between rounded-lg bg-secondary/50 p-3 text-sm"><span>{e.exception_date}{e.note?` • ${e.note}`:""}</span><button onClick={()=>removeException(e.id)} className="rounded-lg p-2 text-destructive hover:bg-destructive/10"><Trash2 className="h-4 w-4"/></button></div>)}</div></section></>}
 {message&&<div className="rounded-xl border bg-card p-3 text-sm">{message}</div>}</div>;
}
