import { useEffect, useState } from "react";
import { Ambulance, Plus, Trash2, Save, Phone, MapPin } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const empty={name:"",phone:"",alternate_phone:"",address:"",service_area:"",ambulance_type:"",latitude:"",longitude:"",is_available:true,is_verified:false,description:""};
export default function AmbulanceManagePage(){
 const [rows,setRows]=useState([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 async function load(){setLoading(true); const {data}=await supabase.from("ambulance_services").select("*").order("name"); setRows(data||[]); setLoading(false)}
 useEffect(()=>{load()},[]);
 async function save(){setSaving(true); const payload={...form,latitude:form.latitude?Number(form.latitude):null,longitude:form.longitude?Number(form.longitude):null}; const q=editing?supabase.from("ambulance_services").update(payload).eq("id",editing):supabase.from("ambulance_services").insert(payload); await q; setSaving(false); setEditing(null);setForm(empty);load()}
 async function remove(id){if(confirm("এই অ্যাম্বুলেন্সটি মুছে ফেলবেন?")){await supabase.from("ambulance_services").delete().eq("id",id);load()}}
 return <div className="space-y-5"><div><h1 className="text-xl font-bold">অ্যাম্বুলেন্স ব্যবস্থাপনা</h1><p className="mt-1 text-sm text-muted-foreground">ডিরেক্টরিতে থাকা অ্যাম্বুলেন্স সার্ভিস যোগ, সম্পাদনা ও মুছে ফেলুন।</p></div>
 <div className="rounded-2xl border bg-card p-4"><h2 className="font-semibold">{editing?"অ্যাম্বুলেন্স সম্পাদনা":"নতুন অ্যাম্বুলেন্স যোগ করুন"}</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{[["name","নাম"],["phone","ফোন"],["alternate_phone","বিকল্প ফোন"],["address","ঠিকানা"],["service_area","সেবা এলাকা"],["ambulance_type","ধরন"],["latitude","Latitude"],["longitude","Longitude"]].map(([k,l])=><Input key={k} placeholder={l} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<textarea className="min-h-20 rounded-lg border bg-background p-3 text-sm sm:col-span-2" placeholder="বিবরণ" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="mt-3 flex flex-wrap gap-4 text-sm"><label><input type="checkbox" checked={form.is_available} onChange={e=>setForm({...form,is_available:e.target.checked})}/> সেবা চালু</label><label><input type="checkbox" checked={form.is_verified} onChange={e=>setForm({...form,is_verified:e.target.checked})}/> যাচাই করা</label></div><div className="mt-3 flex gap-2"><Button onClick={save} disabled={saving||!form.name||!form.phone}><Save className="h-4 w-4"/> {saving?"সংরক্ষণ হচ্ছে...":"সংরক্ষণ"}</Button>{editing&&<Button variant="outline" onClick={()=>{setEditing(null);setForm(empty)}}>বাতিল</Button>}</div></div>
 <div className="space-y-2">{loading?<p className="text-sm text-muted-foreground">লোড হচ্ছে...</p>:rows.map(r=><div key={r.id} className="rounded-xl border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{r.name}</h3><p className="mt-1 text-sm text-muted-foreground"><Phone className="mr-1 inline h-3.5 w-3.5"/>{r.phone} {r.address&&<><MapPin className="ml-2 mr-1 inline h-3.5 w-3.5"/>{r.address}</>}</p></div><Ambulance className="h-5 w-5 text-primary"/></div><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>{setEditing(r.id);setForm({...empty,...r,latitude:r.latitude||"",longitude:r.longitude||""})}}>সম্পাদনা</Button><Button size="sm" variant="destructive" onClick={()=>remove(r.id)}><Trash2 className="h-4 w-4"/> মুছুন</Button></div></div>)}</div></div>
}
