import { useEffect, useMemo, useState } from "react";
import { Droplets, MapPin, Phone, Search, ShieldCheck, ClipboardList, Navigation, RefreshCw } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { ROLES } from "@/constants/roles";
import { BLOOD_GROUPS } from "@/hooks/useBloodBank";
import { fetchAdminBloodDonors, fetchAdminBloodRequests, setAdminBloodDonorAvailability } from "@/services/adminMedicalService";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import LoadingSpinner from "@/components/shared/LoadingSpinner.jsx";

const STATUS_LABEL={pending:"অপেক্ষমাণ",accepted:"গৃহীত",declined:"প্রত্যাখ্যাত",cancelled:"বাতিল",completed:"সম্পন্ন"};
export default function BloodDonorManagePage(){
 const{role}=useAuth();const isSuper=role===ROLES.SUPER_ADMIN;const[tab,setTab]=useState("donors");const[donors,setDonors]=useState([]);const[requests,setRequests]=useState([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(null);
 const[filters,setFilters]=useState({search:"",bloodGroup:"",district:"",upazila:"",availableOnly:false});
 async function load(){setLoading(true);const [d,r]=await Promise.all([fetchAdminBloodDonors(filters),fetchAdminBloodRequests()]);setDonors(d.data||[]);setRequests(r.data||[]);setLoading(false);}
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t);},[filters.search,filters.bloodGroup,filters.district,filters.upazila,filters.availableOnly]);
 async function moderate(d,nextAvailable,nextRequests=d.blood_accept_requests){setBusy(d.user_id);const{error}=await setAdminBloodDonorAvailability(d.user_id,nextAvailable,nextRequests);setBusy(null);if(error)window.alert(error.message);else load();}
 const activeRequests=useMemo(()=>requests.filter(r=>['pending','accepted'].includes(r.status)).length,[requests]);
 return <div className="space-y-5">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-xl font-bold">রক্তদাতা ও রক্তের অনুরোধ</h1><p className="text-sm text-muted-foreground">নাম, ফোন, ঠিকানা, উপলভ্যতা ও রক্তের অনুরোধের অবস্থা এক জায়গায় দেখুন।</p></div><Button variant="outline" onClick={load}><RefreshCw className="h-4 w-4"/> রিফ্রেশ</Button></div>
  <div className="flex gap-2"><Button size="sm" variant={tab==='donors'?'default':'outline'} onClick={()=>setTab('donors')}><Droplets className="h-4 w-4"/> রক্তদাতা ({donors.length})</Button><Button size="sm" variant={tab==='requests'?'default':'outline'} onClick={()=>setTab('requests')}><ClipboardList className="h-4 w-4"/> রক্তের অনুরোধ ({activeRequests} সক্রিয়)</Button></div>
  {tab==='donors'&&<><div className="grid gap-2 rounded-2xl border bg-card p-4 sm:grid-cols-2 lg:grid-cols-5"><label className="relative lg:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="নাম বা ফোন" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label><select className="h-10 rounded-lg border bg-background px-3 text-sm" value={filters.bloodGroup} onChange={e=>setFilters({...filters,bloodGroup:e.target.value})}><option value="">সব রক্তের গ্রুপ</option>{BLOOD_GROUPS.map(g=><option key={g}>{g}</option>)}</select><Input placeholder="জেলা" value={filters.district} onChange={e=>setFilters({...filters,district:e.target.value})}/><Input placeholder="উপজেলা" value={filters.upazila} onChange={e=>setFilters({...filters,upazila:e.target.value})}/><label className="flex items-center gap-2 text-sm lg:col-span-5"><input type="checkbox" checked={filters.availableOnly} onChange={e=>setFilters({...filters,availableOnly:e.target.checked})}/> শুধু বর্তমানে উপলভ্য রক্তদাতা</label></div>
  {loading?<LoadingSpinner label="রক্তদাতা লোড হচ্ছে..."/>:!donors.length?<div className="rounded-2xl border p-8 text-center text-sm text-muted-foreground">কোনো রক্তদাতা পাওয়া যায়নি।</div>:<div className="grid gap-3 xl:grid-cols-2">{donors.map(d=><div key={d.user_id} className="rounded-2xl border bg-card p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{d.full_name||"নাম নেই"}</h2><span className="rounded-full bg-red-50 px-2 py-0.5 text-xs font-bold text-red-600">{d.blood_group||"—"}</span>{d.blood_is_available&&<span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs text-primary">উপলভ্য</span>}</div><p className="mt-2 flex items-center gap-1 text-sm"><Phone className="h-4 w-4 text-muted-foreground"/>{d.phone||"ফোন নেই"}</p><p className="mt-1 flex items-start gap-1 text-sm text-muted-foreground"><MapPin className="mt-0.5 h-4 w-4 shrink-0"/>{d.blood_address||d.address||[d.location_upazila,d.location_district].filter(Boolean).join(', ')||"ঠিকানা নেই"}</p><p className="mt-1 text-xs text-muted-foreground">শেষ রক্তদান: {d.last_blood_donation_date||"তথ্য নেই"} • অনুরোধ গ্রহণ: {d.blood_accept_requests?"চালু":"বন্ধ"} • প্রকাশ্য ফোন: {d.blood_public_phone?"চালু":"বন্ধ"}</p></div>{isSuper&&d.latitude!=null&&d.longitude!=null&&<a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${d.latitude},${d.longitude}`} className="inline-flex min-h-10 shrink-0 items-center gap-1 rounded-lg border px-3 text-xs font-semibold text-primary"><Navigation className="h-4 w-4"/> Maps</a>}</div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busy===d.user_id} onClick={()=>moderate(d,!d.blood_is_available)}>{d.blood_is_available?"অনুপলভ্য করুন":"উপলভ্য করুন"}</Button><Button size="sm" variant="outline" disabled={busy===d.user_id} onClick={()=>moderate(d,d.blood_is_available,!d.blood_accept_requests)}>{d.blood_accept_requests?"অনুরোধ বন্ধ করুন":"অনুরোধ চালু করুন"}</Button></div></div>)}</div>}</>}
  {tab==='requests'&&(loading?<LoadingSpinner label="রক্তের অনুরোধ লোড হচ্ছে..."/>:<div className="space-y-3">{requests.length?requests.map(r=><div key={r.id} className="rounded-2xl border bg-card p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold">{r.blood_group} রক্ত • {r.requester_name||"রোগী"} → {r.donor_name||"রক্তদাতা"}</p><p className="mt-1 text-sm text-muted-foreground">{r.request_number?`#${r.request_number} • `:""}রোগী: {r.requester_phone||"ফোন নেই"} • দাতা: {r.donor_phone||"ফোন নেই"} • {r.needed_date||"তারিখ নেই"}{r.needed_time?` • ${r.needed_time}`:""}</p><p className="mt-2 text-sm">{r.reason}</p>{(r.hospital_name||r.location_text)&&<p className="mt-1 text-xs text-muted-foreground">স্থান: {[r.hospital_name,r.location_text].filter(Boolean).join(' — ')}</p>}</div><span className="h-fit rounded-full bg-secondary px-3 py-1 text-xs font-medium">{STATUS_LABEL[r.status]||r.status}</span></div></div>):<div className="rounded-2xl border p-8 text-center text-sm text-muted-foreground">কোনো রক্তের অনুরোধ নেই।</div>}</div>)}
 </div>;
}
